project:
  type: website
  output-dir: _site
  render:
    - other/intro-presentation.qmd
    - lessons/lesson_01_intro.qmd
    - lessons/lesson_02_old_new_stats.qmd
    - lessons/lesson_03_duckdb.qmd
    - lessons/lesson_04_superset.qmd

website:
  title: "mgimo-foreign-trade"
  navbar:
    left:
      - text: "Вводная презентация"
        href: other/intro-presentation.qmd
      - text: "Занятие 1"
        href: lessons/lesson_01_intro.qmd
      - text: "Занятие 2"
        href: lessons/lesson_02_old_new_stats.qmd
      - text: "Занятие 3"
        href: lessons/lesson_03_duckdb.qmd
      - text: "Занятие 4"
        href: lessons/lesson_04_superset.qmd

format:
  html:
    theme: cosmo
